### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by Turmac** [StephenOman/Python-ML#1]
When I run your code, the outputs are either all 0's or all 1's.
I made the following changes to make it work:
In xor_nn.py, since there is negative sign in the activate function already, there is no need to put negative sign in line 20 and line 22:
`A2 = np.vstack(([1], sigmoid(-Z2)))`
`h = sigmoid(-Z3)`
In timetest.py, change the learning rate to 0.1.

**Comment by StephenOman** [comment]
Thanks for the note. The negative sign is indeed incorrect and has been fixed.

I've left the learning rate at 0.01, but changed the number of epochs to get a better chance at converging the network.
